CREATE TABLE buildings (
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	geometry GEOMETRY(POLYGON, 0),
	name VARCHAR(50)
);

CREATE TABLE roads (
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	geometry GEOMETRY(LINESTRING, 0),
	name VARCHAR(50)
);

CREATE TABLE poi (
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	geometry GEOMETRY(POINT, 0),
	name VARCHAR(50)
);